version: 3
updates:
  # Bundler（RubyGems）の更新設定 (main 向け)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily" # 毎日チェック
    target-branch: "main" # ★ `main` に変更
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "auto-merge"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

