version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily" # 毎日チェック
    target-branch: "main" # main ブランチ向け
    open-pull-requests-limit: 1  # 1 つの PR のみ許可
    labels:
      - "dependencies"
      - "auto-merge"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    groups:
      bundler-all:
        patterns:
          - "*"  # すべての依存関係を対象にグループ化

