version: 2
updates:
  # Bundler（RubyGems）の更新設定 (stagingブランチ向け)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "staging"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "auto-merge"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Bundler（RubyGems）の更新設定 (mainブランチ向け)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly" # mainブランチの更新頻度は weekly に設定
    target-branch: "main"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

