version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test

