version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:3.2 # Ruby 3.2 の環境を使用
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test

