name: Auto Merge PRs on Creation

on:
  pull_request:
    types:
      - opened

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto merge PR
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Merging PR #$PR_NUMBER"
          gh pr merge "$PR_NUMBER" --squash --auto

